# Generated by Django 4.0.4 on 2023-02-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('Computer', 'Computer'), ('AIML', 'AIML'), ('Data Science', 'Data Science'), ('IOT', 'IOT')], max_length=50)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=50)),
                ('rollNumber', models.PositiveIntegerField()),
                ('erp', models.PositiveBigIntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed')], max_length=50)),
                ('totalMoney', models.PositiveIntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('eventDate', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='SubCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('Computer', 'Computer'), ('AIML', 'AIML'), ('Data Science', 'Data Science'), ('IOT', 'IOT')], max_length=50)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=50)),
                ('rollNumber', models.PositiveIntegerField()),
                ('erp', models.PositiveBigIntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.coordinator')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='subevents')),
                ('money', models.PositiveIntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('eventDate', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.coordinator')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.event')),
                ('subcoordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.subcoordinator')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('Computer', 'Computer'), ('AIML', 'AIML'), ('Data Science', 'Data Science'), ('IOT', 'IOT')], max_length=50)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=50)),
                ('rollNumber', models.PositiveIntegerField()),
                ('erp', models.PositiveBigIntegerField()),
                ('isVolunteer', models.BooleanField(default=False)),
                ('work', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.event')),
                ('subevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.subevent')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('feeApplicableForPerStudent', models.PositiveIntegerField()),
                ('fundRecieveFromCollege', models.PositiveIntegerField()),
                ('hodApproval', models.BooleanField(default=False)),
                ('adminApproval', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed')], max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentRecieptImage', models.ImageField(upload_to='payment')),
                ('recieptNumber', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('Computer', 'Computer'), ('AIML', 'AIML'), ('Data Science', 'Data Science'), ('IOT', 'IOT')], max_length=50)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=50)),
                ('rollNumber', models.PositiveIntegerField()),
                ('erp', models.PositiveBigIntegerField()),
                ('whatsAppNumber', models.CharField(max_length=10)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('coordinatorCheck', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('Computer', 'Computer'), ('AIML', 'AIML'), ('Data Science', 'Data Science'), ('IOT', 'IOT')], max_length=50)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=50)),
                ('rollNumber', models.PositiveIntegerField()),
                ('erp', models.PositiveBigIntegerField()),
                ('isParticipant', models.BooleanField(default=False)),
                ('interest', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.event')),
                ('subevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.subevent')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Memories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memories')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.event')),
                ('subevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.subevent')),
            ],
        ),
    ]
