# Generated by Django 4.1.6 on 2023-02-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite_app', '0002_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
