# Generated by Django 4.1.6 on 2023-02-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite_app', '0003_event_upi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subevent',
            old_name='money',
            new_name='balanceBudget',
        ),
        migrations.AddField(
            model_name='subevent',
            name='totalBudget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subevent',
            name='utiliseBudget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
