# Generated by Django 4.1.6 on 2023-02-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite_app', '0004_rename_money_subevent_balancebudget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('uuid', models.UUIDField(unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.event')),
            ],
        ),
    ]
