# Generated by Django 4.1.6 on 2023-02-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite_app', '0007_pass_createdat_pass_updatedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='updatedAt',
        ),
    ]
