# Generated by Django 4.0.2 on 2023-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite_app', '0009_pass_createdat_pass_updatedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='adminApproval',
            new_name='HoD_Approval',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='hodApproval',
            new_name='Principal_Approval',
        ),
        migrations.AddField(
            model_name='proposal',
            name='Vice_Principal_Approval',
            field=models.BooleanField(default=False),
        ),
    ]
