# Generated by Django 4.0.2 on 2023-04-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite_app', '0010_rename_adminapproval_proposal_hod_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='coordinator',
        ),
    ]
