# Generated by Django 4.0.2 on 2023-04-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite_app', '0011_remove_proposal_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='coordinator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventbrite_app.coordinator'),
            preserve_default=False,
        ),
    ]
