# Generated by Django 4.0.2 on 2023-04-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite_app', '0014_alter_coordinator_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='username',
        ),
    ]
