# Generated by Django 4.0.2 on 2023-04-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite_app', '0015_remove_coordinator_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcoordinator',
            name='username',
        ),
    ]
