# Generated by Django 4.0.2 on 2023-04-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite_app', '0016_remove_subcoordinator_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='modeOfPayment',
            field=models.CharField(choices=[('CASH', 'CASH'), ('ONLINE', 'ONLINE')], default='CASH', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentRecieptImage',
            field=models.ImageField(blank=True, null=True, upload_to='payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recieptNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
