# Generated by Django 4.0.2 on 2023-04-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite_app', '0017_payment_modeofpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='modeOfPayment',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('ONLINE', 'ONLINE')], default='CASH', max_length=100, null=True),
        ),
    ]
